// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRkhVabU_Ia42Qm8ul9XjKuNsjhx9jB0A',
    appId: '1:172061406796:web:2810cb971908d39a2a26e9',
    messagingSenderId: '172061406796',
    projectId: 'dr-saathi',
    authDomain: 'dr-saathi.firebaseapp.com',
    storageBucket: 'dr-saathi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIEzVDmV8ujyT7wrivt7rqELXmMNeoIHg',
    appId: '1:172061406796:android:d1957c2268df99272a26e9',
    messagingSenderId: '172061406796',
    projectId: 'dr-saathi',
    storageBucket: 'dr-saathi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeMfLmKQ_1RdQDfrBKa4AiW--BxjFUZh4',
    appId: '1:172061406796:ios:1eaf7fdf82f88a7a2a26e9',
    messagingSenderId: '172061406796',
    projectId: 'dr-saathi',
    storageBucket: 'dr-saathi.firebasestorage.app',
    iosBundleId: 'com.drsaathi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeMfLmKQ_1RdQDfrBKa4AiW--BxjFUZh4',
    appId: '1:172061406796:ios:7547f40e4cf4ae522a26e9',
    messagingSenderId: '172061406796',
    projectId: 'dr-saathi',
    storageBucket: 'dr-saathi.firebasestorage.app',
    iosBundleId: 'com.example.drSaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRkhVabU_Ia42Qm8ul9XjKuNsjhx9jB0A',
    appId: '1:172061406796:web:2810cb971908d39a2a26e9',
    messagingSenderId: '172061406796',
    projectId: 'dr-saathi',
    authDomain: 'dr-saathi.firebaseapp.com',
    storageBucket: 'dr-saathi.firebasestorage.app',
  );
}
